[package]
name = "suivm"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
cfg-if = "1.0.0"
anyhow = "1.0.32"
dirs = "1.0.5"
semver = "1.0.4"
serde = { version = "1.0.136", features = [ "derive" ]}
serde_json = "1.0.78"
thiserror = "1.0.30"
once_cell = { version = "1.8.0" }
reqwest = { version = "0.11.9", features = ['blocking', 'json', 'stream'] }
tempfile = "3.3.0"
indicatif = "0.17.1"